### ISSUE TITLE
Unable to open AI view

### ISSUE THREAD

**Issue by vitezprchal** [clinebot/cline#487]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude

### What happened?

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### Steps to reproduce

1. Open IDE - Visual Studio Code

**Comment by saoudrizwan** [comment]
This is probably because you're using an old version of vscode. Please update to the latest and if that doesn't work try the troubleshooting steps here https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai 
Feel free to re-open if you're still seeing this issue.
